language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - python pyeventbus/tests/performance_testing.py startCPUHeavyTestInMain
  - python pyeventbus/tests/performance_testing.py startCPUHeavyTestInBackground
  - python pyeventbus/tests/performance_testing.py startCPUHeavyTestInGreenlet
  - python pyeventbus/tests/performance_testing.py startCPUHeavyTestInParallel
  - python pyeventbus/tests/performance_testing.py startCPUHeavyTestInConcurrent