# Python 2

python2 network_performance_testing.py startNetworkHeavyTestInMain
python2 network_performance_testing.py startNetworkHeavyTestInBackground
python2 network_performance_testing.py startNetworkHeavyTestInGreenlet
python2 network_performance_testing.py startNetworkHeavyTestInParallel
python2 network_performance_testing.py startNetworkHeavyTestInConcurrent
python2 IO_performance_testing.py startIOHeavyTestInMain
python2 IO_performance_testing.py startIOHeavyTestInBackground
python2 IO_performance_testing.py startIOHeavyTestInGreenlet
python2 IO_performance_testing.py startIOHeavyTestInParallel
python2 IO_performance_testing.py startIOHeavyTestInConcurrent
python2 performance_testing.py startCPUHeavyTestInMain
python2 performance_testing.py startCPUHeavyTestInBackground
python2 performance_testing.py startCPUHeavyTestInGreenlet
python2 performance_testing.py startCPUHeavyTestInParallel
python2 performance_testing.py startCPUHeavyTestInConcurrent

