
# Python 3
python3 network_performance_testing.py startNetworkHeavyTestInMain
python3 network_performance_testing.py startNetworkHeavyTestInBackground
python3 network_performance_testing.py startNetworkHeavyTestInGreenlet
python3 network_performance_testing.py startNetworkHeavyTestInParallel
python3 network_performance_testing.py startNetworkHeavyTestInConcurrent
python3 IO_performance_testing.py startIOHeavyTestInMain
python3 IO_performance_testing.py startIOHeavyTestInBackground
python3 IO_performance_testing.py startIOHeavyTestInGreenlet
python3 IO_performance_testing.py startIOHeavyTestInParallel
python3 IO_performance_testing.py startIOHeavyTestInConcurrent
python3 performance_testing.py startCPUHeavyTestInMain
python3 performance_testing.py startCPUHeavyTestInBackground
python3 performance_testing.py startCPUHeavyTestInGreenlet
python3 performance_testing.py startCPUHeavyTestInParallel
python3 performance_testing.py startCPUHeavyTestInConcurrent
python3 threadPool_performance_testing.py startCPUHeavyTestInBackground 0
python3 threadPool_performance_testing.py startCPUHeavyTestInBackground 1
python3 threadPool_performance_testing.py startCPUHeavyTestInBackground 5

